import { lazy } from 'react';

export const EngineRegistry: Record<string, React.LazyExoticComponent<any>> = {
  'Interactive Engine': lazy(() => import('../implementations/InteractiveEngine')),
  'Integer Engine': lazy(() => import('../implementations/IntegerEngine')),
  'Triangle Engine': lazy(() => import('../implementations/TriangleEngine')),
  'Fraction Engine': lazy(() => import('../implementations/FractionEngine')),
  'Rotation Engine': lazy(() => import('../implementations/RotationEngine')),
  'Polygon Engine': lazy(() => import('../implementations/PolygonEngine')),
  'Light Engine': lazy(() => import('../implementations/physics/PhysicsEngine')),
  'Physics Engine': lazy(() => import('../implementations/physics/PhysicsEngine')),
  'Electric Circuit Engine': lazy(() => import('../implementations/physics/PhysicsEngine')),
  'Magnetism Engine': lazy(() => import('../implementations/physics/PhysicsEngine')),
  'Chemistry Engine': lazy(() => import('../implementations/chemistry/ChemistryEngine')),
  'Periodic Table Engine': lazy(() => import('../implementations/chemistry/ChemistryEngine')),
  'Molecule Engine': lazy(() => import('../implementations/chemistry/ChemistryEngine')),
  'Chemical Reaction Engine': lazy(() => import('../implementations/chemistry/ChemistryEngine')),
  'Biology Engine': lazy(() => import('../implementations/biology/BiologyEngine')),
  'Plant Cell Engine': lazy(() => import('../implementations/biology/BiologyEngine')),
  'Animal Cell Engine': lazy(() => import('../implementations/biology/BiologyEngine')),
  'Cell Engine': lazy(() => import('../implementations/biology/BiologyEngine')),
  'Anatomy Engine': lazy(() => import('../implementations/biology/BiologyEngine')),
  'Cube Engine': lazy(() => import('../implementations/mensuration/MensurationEngine')),
  'Cuboid Engine': lazy(() => import('../implementations/mensuration/MensurationEngine')),
  'Cylinder Engine': lazy(() => import('../implementations/mensuration/MensurationEngine')),
  'Circle Engine': lazy(() => import('../implementations/mensuration/MensurationEngine')),
  'Cone Engine': lazy(() => import('../implementations/mensuration/MensurationEngine')),
  'Coordinate Engine': lazy(() => import('../implementations/CoordinateEngine')),
  'Graph Engine': lazy(() => import('../implementations/GraphEngine')),
  'Number Line Engine': lazy(() => import('../implementations/NumberLineEngine')),
  'Probability Engine': lazy(() => import('../implementations/statistics/StatisticsEngine')),
  'Statistics Engine': lazy(() => import('../implementations/statistics/StatisticsEngine')),
  'Mensuration Engine': lazy(() => import('../implementations/mensuration/MensurationEngine')),
  'Algebra Engine': lazy(() => import('../implementations/algebra/AlgebraEngine')),
};
